[package]
name = "leet-code"
version = "0.1.0"
authors = ["Idan Loo <im@siwei.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
time = "0.1.42" 